data:
  trainpath: '/mounts/datasets/datasets/2025-ZooCamChallenge/train'
  testpath: '/mounts/datasets/datasets/2025-ZooCamChallenge/test'
  batch_size: 64
  num_workers: 4
  valid_ratio: 0.1
  seed: 42

  img_size: 192
  to_rgb: true
  pad_fill: 255

  analysis:
    compute_analysis: false
    out_dir: './analysis'
    compute_percentiles: true

optim:
  algo: AdamW
  params:
    lr: 0.0001
    weight_decay: 0.01

scheduler:
  algo: CosineAnnealingLR
  params:
    T_max: 6
    eta_min: 1.0e-6

nepochs: 5
loss: "CrossEntropyLoss"

logging:
  logdir: "./logs"
  wandb:
    project: "ZooCamChallenge"
    entity: null

model:
  class: ResNetClassifier
  name: "resnet50"
  pretrained: true
  freeze_backbone: false
  unfreeze_layer4: true
  head_hidden: 1024
  head_dropout: 0.2

train:
  resume: false
  checkpoint: ""
  # resume: true
  # checkpoint: "./logs/ResNetClassifier50_/best_model.pt"

test:
  checkpoint: "./logs/ResNetClassifier50_1/best_model.pt" 

output:
  submission_path: "./submission.csv"
