data:
  trainpath: '/mounts/datasets/datasets/2025-ZooCamChallenge/train'
  testpath: '/mounts/datasets/datasets/2025-ZooCamChallenge/test'
  batch_size: 64
  num_workers: 4
  valid_ratio: 0.1
  seed: 42

  mean: 0.886471
  std: 0.208829

  img_size: 192
  to_rgb: true
  pad_fill: 255

  analysis:
    compute_analysis: false
    out_dir: './analysis'
    compute_percentiles: true

  sampler:
    enabled: true
    alpha: 0.3
    max_weight: 5.0

optim:
  algo: AdamW
  params:
    lr: 0.0001
    weight_decay: 0.01

scheduler:
  algo: CosineAnnealingLR
  params:
    T_max: 6
    eta_min: 1.0e-6

nepochs: 5
loss: "CrossEntropyLoss"

logging:
  logdir: "./logs"
  wandb:
    project: "ZooCamChallenge"
    entity: null

model:
  class: ResNetClassifier
  name: "resnet50"
  pretrained: true
  freeze_backbone: false
  unfreeze_layer4: true
  head_hidden: 1024
  head_dropout: 0.2

train:
  resume: false
  checkpoint: ""
  # resume: true
  # checkpoint: "./logs/ResNetClassifier50_/best_model.pt"

test:
  checkpoint: "./logs/ResNetClassifier50_1/best_model.pt"
  use_tta: true
  tta_names: ["orig", "hflip", "vflip", "rot180"]
  tta_weights: null

inference:
  tta:
    - orig
    - hflip
    - vflip
    - rot180
    - rot90
    - rot270
  tta_norm_mean: [0.886471, 0.886471, 0.886471]
  tta_norm_std: [0.208829, 0.208829, 0.208829]
  logit_adjustment_tau_grid: [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0]
  sweep_logit_adjustment: true

output:
  submission_path: "./outputs/submission_resnet_tta_optimized.csv"
